correct title param for release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,10 +23,10 @@ jobs:
             echo "Error: Tag ${{ github.event.inputs.tag }} does not exist"
             exit 1
           fi
-          # if [ "$(git rev-parse ${{ github.event.inputs.tag }})" != "$(git rev-parse main~0)" ]; then
-          #   echo "Error: Tag ${{ github.event.inputs.tag }} is not at the tip of main branch"
-          #   exit 1
-          # fi
+          if [ "$(git rev-parse ${{ github.event.inputs.tag }})" != "$(git rev-parse main~0)" ]; then
+            echo "Error: Tag ${{ github.event.inputs.tag }} is not at the tip of main branch"
+            exit 1
+          fi
 
       # - name: Fetch all tags
       #   run: git fetch --tags
@@ -110,7 +110,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           gh release create ${{ github.event.inputs.tag }} \
-            --title= ${{ github.event.inputs.tag }} \
+            --title="${{ github.event.inputs.tag }}" \
             --generate-notes \
             *.zip
       # - name: Create GitHub Release
